[package]
name = "rust_exp"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_exp_lib = { path = "../rust_exp_lib" }
